// lib/diagram_utils.ts

export function getDiagramSrc(manifest: Record<string, Record<string, unknown>>, key: string): string | null {
  const item = manifest[key];
  if (!item) return null;

  // 1. High-res vector preview URL generated by diagram_renderer
  if (item.preview_url && typeof item.preview_url === "string") {
    return item.preview_url;
  }

  // 2. Direct local disk image generated by diagram_renderer
  const pathStr = typeof item.image_path === "string" ? item.image_path : typeof item.path === "string" ? item.path : "";
  if (pathStr) {
    const filename = pathStr.split(/[/\\]/).pop();
    return `http://localhost:8000/api/diagram-image/${filename}`;
  }

  return null;
}
